### ISSUE TITLE
Flat lines 

### ISSUE THREAD

**Issue by stevezall** [mathieudutour/TimeLines#39]
Referenced in bug #38 

Lines are flat now (pre sunset). Sunset here is 8:30 (Milwaukee WI USA)

![0E288223-8991-4D4D-8AAC-8D2BB2138618](https://user-images.githubusercontent.com/46692877/84330567-5d0a2980-ab4d-11ea-8a60-1230d47bdfd9.png)

**Comment by stevezall** [comment]
Even with no other contacts 

![69E31285-2EE9-4A26-8689-2B005567DCF1](https://user-images.githubusercontent.com/46692877/84330710-c38f4780-ab4d-11ea-984c-abb6edd2d5c1.png)

**Comment by moorea** [comment]
One thing that I noticed as I poked around the code a bit, was that the body of the `Line` View seems to assume that `startTime` and `endTime` will either _both_ be `nil` or both be not-nil. 

I was able to reproduce a flat line when providing only a `startTime` or only an `endTime`. 

Just for fun, adding something like this at line 491 of `Line.swift` seemed to at least partially solve that problem.
```
    if start != nil && end == nil && coordinate != nil {
        let solar = Solar(coordinate: coordinate!)
        end = solar?.civilSunset
    }
    
    if end != nil && start == nil && coordinate != nil {
        let solar = Solar(coordinate: coordinate!)
        start = solar?.civilSunrise
    }
```

However, this wouldn't explain why @stevezall was seeing a flat line for his "Me" time (since I don't think you can set custom start/end times for "Me"). It also doesn't account for setting a custom `endTime` earlier than a custom `startTime`.

Anyway, only took a cursory glance through the code. Certainly not an expert on the matter. Just thought maybe this could be a clue.

**Comment by mathieudutour** [comment]
> I was able to reproduce a flat line when providing only a startTime or only an endTime.

Ah good catch, I'll fix that.

But yes, this issue is a bit different I think. I'm wondering if it only happens during a certain time of the day (as I think it does based on the discussion in #38).

@stevezall could you check if it only happens in the evening or if it's flat all the time? And it'd be really helpful if you could tell me your rough location so that I can try to reproduce.

**Comment by smstefanik** [comment]
@mathieudutour yeah, seems to be evening. Right now it is 10AM here and it's working
 (using personal GitHub acct to respond, stevezall is work acct)

"here" is Milwaukee, WI USA
43.05°N 87.95°W

**Comment by mathieudutour** [comment]
Ok thanks! 

The fact that it's working during the day but not the evening is super weird. The current shouldn't impact the shape of the curve. So my guess is that the app can't get your position. Because I don't want to ask for the GPS coordinates (really don't need them, I just want a 100km circle), I use a reverse mapping of the timezone name to the center of the position. So, for example, `10 AM America/New York` maps to `40.71416, -74.00639`.

My guess is that during the evening, your timezone is one that I don't know about, and so I bail out. That could explain the flat line.

Now I don't know why the timezone change (do you perhaps commute far?), but I'm going to add the timezone information in the feedback template (from the app). Please submit a new feedback when the new version is out.

**Comment by smstefanik** [comment]
No commute 😄 stuck at home! No where near timezone border either.

I'll see if I can debug the timezone info myself as well

**Comment by smstefanik** [comment]
Got new version

Time Lines 1.0.7 (54) - me.dutour.mathieu.TimeLine
iOS 13.4.1
D421AP
Timezone America/Chicago

Normal lines at 6:30pm, but flat now (sunset 8:30 here)

![EF32FCE6-A16F-45A2-B80E-F5B919989269](https://user-images.githubusercontent.com/533836/84718147-8e179f00-af3d-11ea-97ea-aebcc8e02c8f.png)

**Comment by mathieudutour** [comment]
I *think* I have a fix. Let me know if v1.0.8 fixes it

**Comment by smstefanik** [comment]
yes, appears to work now!
